### PR TITLE
Lab 6 Pull Request - UI/UX

### PR DESCRIPTION
**Pull request by oguzkagnici**
## Summary
We have discussed several key elements for overall user experience. As a result, we have noticed that certain aspects can be improved to offer a more enjoyable time. We have worked on feed permanence after clicking into posts and dividing feed into pages to prevent addiction.

### Backend Implementation

These modifications required only mobile and frontend developments. Therefore, backend members focused on creating [User Stories](https://github.com/bounswe/bounswe2024group8/wiki/User-Stories-for-Lab-6) and thinking of other improvements.

### User Stories

[User Stories](https://github.com/bounswe/bounswe2024group8/wiki/User-Stories-for-Lab-6)

### Meeting Notes
[Meeting Notes 7](https://github.com/bounswe/bounswe2024group8/wiki/Meeting-Notes-7-%E2%80%90-Nov-12)

### CODE REVIEW

**Comment by yektaercul** [comment]
-In lab time I finished the gcp file service in this [pr](https://github.com/bounswe/bounswe2024group8/pull/290) for Tuluyhan to implement it in the post creation method.
-Reviewed and fixed the bugs in these prs and merged them during lab hours:
- [281](https://github.com/bounswe/bounswe2024group8/pull/281)
- [282](https://github.com/bounswe/bounswe2024group8/pull/282)
- [273](https://github.com/bounswe/bounswe2024group8/pull/273)

**Comment by TurkerErdem99** [comment]
[Meeting notes 7](https://github.com/bounswe/bounswe2024group8/wiki/Meeting-Notes-7-%E2%80%90-Nov-12) is added to [wiki](https://github.com/bounswe/bounswe2024group8/wiki). [Lab 6 PR](https://github.com/bounswe/bounswe2024group8/pull/295) description is edited accordingly.

**Comment by TurkerErdem99** [comment]
The issues that are created and worked on in this lab are listed below:

- [#279](https://github.com/bounswe/bounswe2024group8/issues/279)
- [#280](https://github.com/bounswe/bounswe2024group8/issues/280)
- [#286](https://github.com/bounswe/bounswe2024group8/issues/286)
- [#287](https://github.com/bounswe/bounswe2024group8/issues/287)
- [#288](https://github.com/bounswe/bounswe2024group8/issues/288)
- [#289](https://github.com/bounswe/bounswe2024group8/issues/289)
- [#291](https://github.com/bounswe/bounswe2024group8/issues/291)
- [#292](https://github.com/bounswe/bounswe2024group8/issues/292)
- [#294](https://github.com/bounswe/bounswe2024group8/issues/294)
- [#296](https://github.com/bounswe/bounswe2024group8/issues/296)
- [#297](https://github.com/bounswe/bounswe2024group8/issues/297)

**Comment by TurkerErdem99** [comment]
The description, the implementations and the features, which were expected to be done within the lab session, seems okay for this lab.

**Comment by AliAlperenSonmez** [comment]
I worked on the following issues for this lab:
https://github.com/bounswe/bounswe2024group8/issues/302
https://github.com/bounswe/bounswe2024group8/issues/301
https://github.com/bounswe/bounswe2024group8/issues/300
https://github.com/bounswe/bounswe2024group8/issues/299

**Pull request merged**
