### PR TITLE
Lab8

### PR DESCRIPTION
**Pull request by TurkerErdem99**
## Meeting Notes - Dec 3

[Link](https://github.com/bounswe/bounswe2024group8/wiki/Meeting-Notes-9-%E2%80%90-Dec-3)

 # Checklist

## Primary Features

- [X] PF1 - Semantic Search:

We have implemented semantic search feature using Wikidata to enhance browsing results. When a keyword is searched, corresponding child instance is found in Wikidata and other sibling instances from the parent classes are fetched. Then, they are also being searched in the database

- [X] PF2 - Achievements:

Achievements are the main method that is utilized for distinguishing users based on their activity on our app. Users can be awarded in response to several actions, such as receiving likes, liking other posts, commenting, bookmarking etc.

- [X] PF3 - User Management:

We have implemented various user management features to offer a more personalized experience. Users can follow/unfollow other users and categories to create a feed page tailored to their specific interests. Furthermore, they can also upload a custom profile picture to have a more customized, distinguishable account.

- [X] PF4 - Tournaments:

Tournaments are one of the core features that allow users to interact with others in a competitive manner. Every week, fully automated tournaments begin under every category and users can join those via creating their unique designs. Then, they get a ranking according to the received interaction with their posts.

### Acceptance Criteria & Examples

PF1:

- Users shall be able to retrieve search post results that contain the searched keyword in their title, tags.
- Users shall be able to retrieve other search post results that contain keywords, which can be fetched using the Wikidata subclass property.

As an example, when "couch" is searched, related seating items should also be returned, such as bench, sofa and chair.

PF2:

- Users shall be able to earn achievements and view them on their profile when required activity is done.

As an example, users should earn "Commenter" achievement and corresponding experience points when they comment on a post.

PF3:

- Users shall be able to update their profile picture
- Users shall be able to follow/unfollow other users
- Users shall be able to follow/unfollow categories

As an example, when users upload ".jpeg" format images to set as their profile picture, it can be viewed by other users in their profile. Furthermore, when a user or a category is followed, its content can be viewed in the feed.

PF4:

- Users shall be able to join tournaments under categories with their own posts.
- Users shall be ranked based on the interaction they received with the entered post.
- Users shall be awarded with the prize when they finish weekly tournaments in top 3.

As an example, when a user joins the tournament and receives the highest interaction, he/she should earn 30 experience points.

## Domain-Specific Features

- [x] DSF1 - Implement 3d viewer library in frontend and mobile to showcase 3d files: Online-3d-viewer:

We have implemented Online-3d-viewer library to let users interact with 3d supported files in both mobile and frontend. 

- [x] DSF2 - Implement and connect GCP bucket to store 3d-supported files and profile pictures:

We have implemented GCP bucket connection methods in our Spring Boot backend which returns corresponding download url for our backend to store and for our mobile and front to download.

### Acceptance Criteria & Examples

DSF1:

- Should accept and show files with extensions .obj .dae . 
- Should show files up to 10 MB.

DSF2:

- Should accept and store files with extensions .obj .dae .jpeg .png . 
- Should accept files up to 10MB.
- Should provide a public url for frontend and mobile.

## API and Documentation

- [x] AD1 - Swagger Implementation for backend REST API:
We have configured the swagger OpenAPI in our backend. Configured endpoints that requires Multimedia upload separately. Added configuration to easily authorize a user after login. 

- [x] AD2 - Customize and elaborate endpoint examples and descriptions with swagger configurations for documentation:
  All primary endpoints should have descriptions and correct possible return http statuses. 

- [x] AD3 - User Search Endpoint Implementation:
Users can search other users by username using the search bar. Should return similar usernames according to given query string. 

### Acceptance Criteria & Examples

AD1:

- Should be available in live environment.
- Should be compatible with Multimedia required endpoints.
- Should be configured to easily authorize.

AD2:

- Primary endpoints should include a description in swagger page.
- Primary endpoints should show correct possible http response statuses with example bodies.

AD3:

- Should return users with username similar to given query string.
- Should match with case insensitive approach.

## Standard(s) Being Followed

In 3Design project, we planned to use W3C Web Annotation Data Model Standard. Here are the items that will determine if we achieved the compliance with W3C Web Annotation Data Model Standard.

- [x] S1 - Annotation Protocol Used

Acceptance Criteria & Examples:

W3C Annotation Data Model Standard Annotation Protocol should be researched, implemented and used. Related issue is [here](https://github.com/bounswe/bounswe2024group8/issues/408). After the research, the example will be provided in the issue.

- [ ] S2 Annotation DB/Server Separated

Acceptance Criteria & Examples:

Based on the W3C Annotation Data Model Standard, Annotation Data should be stored in a seperated DB and should be served from a separated server other than backend. Related research and implementations should be done. Related issue is [here](https://github.com/bounswe/bounswe2024group8/issues/409). After the research, the example will be provided in the issue.

- [X] S3 Annotation Response Format is JSON-LD

Acceptance Criteria & Examples:

The data model of the response for annotation requests should be in JSON-LD format. Example response is here:

```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno6",
  "type": "Annotation",
  "bodyValue": "Comment text",
  "creator": {
    "id": "http://example.org/user1",
    "type": "Person",
    "nickname": "pseudo"
  },
  "created": "2021-06-01T12:00:00Z",
  "target": {
    "source": "http://example.org/ebook1",
    "selector": {
      "type": "TextPositionSelector",
      "start": 412,
      "end": 795
    }
  }
}
``` 

- [X] S4 Public Access to Annotation Feature FE

Acceptance Criteria & Examples:

Any user that is logged in shall be able to create annotations and view all users' annotations using web UI (frontend). For example, after login on web UI and navigating to a post page, the user shall be able to view the annotations from other users and create a new annotation by selecting part of the text in the post page. User shall be able to view the username, annotation body and annotated text for each annotation. 

- [x] S5 Public Access to Annotation Feature Mobile

Acceptance Criteria & Examples:

Any user that is logged in shall be able to create annotations and view all users' annotations using mobile application (mobile). For example, after login on mobile application and navigating to a post page, the user shall be able to view the annotations from other users and create a new annotation by selecting part of the text in the post page. User shall be able to view the username, annotation body and annotated text for each annotation. 

## Testing Strategies
For backend we divided the vital backend services to each of us who are in the backend part of our project. We decided to use JUnit and Mockito to write unit tests.

For frontend we used Jest with TypeScript to test the main parts of the frontend. We focused on testing important components like UI and key features to make sure they work correctly. The tests check if everything behaves as expected and handle different situations properly.

#### Backend
We wrote unit tests for these services: CommentService, FileService, PostService, UserService, TournamentService.
Our main focus was to test exceptions and valid requests to methods of these services.

image

Here is the coverage result of our tests. We prioritized the most used and vital methods.

Related pull requests: [#386](https://github.com/bounswe/bounswe2024group8/pull/386), [#387](https://github.com/bounswe/bounswe2024group8/pull/387), [#390](https://github.com/bounswe/bounswe2024group8/pull/390)

For the final customer milestone, integration testing for backend will be completed. (Related issue: [#399](https://github.com/bounswe/bounswe2024group8/issues/399))

#### Frontend
We wrote unit tests for these components: TournamentInfo, TournamentLeaderboard, SearchResults, Comments. 
All tests are successfull, our components work as expected.

image

Here is the coverage result of our tests. We prioritized the most used and vital components.

Related pull requests: [#397](https://github.com/bounswe/bounswe2024group8/pull/397), [#398](https://github.com/bounswe/bounswe2024group8/pull/398)

#### Backend
All tests pass without errors.
Methods handle valid requests and exceptions correctly.
The most important features and methods are tested.

#### Frontend
All tests pass without errors.
Components are correctly rendered.
The most used and vital components are tested.

### CODE REVIEW

**Comment by oguzkagnici** [comment]
# Checklist

## Primary Features

- [X] PF1 - Semantic Search:

We have implemented semantic search feature using Wikidata to enhance browsing results. When a keyword is searched, corresponding child instance is found in Wikidata and other sibling instances from the parent classes are fetched. Then, they are also being searched in the database

- [X] PF2 - Achievements:

Achievements are the main method that is utilized for distinguishing users based on their activity on our app. Users can be awarded in response to several actions, such as receiving likes, liking other posts, commenting, bookmarking etc.

- [X] PF3 - User Management:

We have implemented various user management features to offer a more personalized experience. Users can follow/unfollow other users and categories to create a feed page tailored to their specific interests. Furthermore, they can also upload a custom profile picture to have a more customized, distinguishable account.

- [X] PF4 - Tournaments:

Tournaments are one of the core features that allow users to interact with others in a competitive manner. Every week, fully automated tournaments begin under every category and users can join those via creating their unique designs. Then, they get a ranking according to the received interaction with their posts.

### Acceptance Criteria & Examples

PF1:

- Users shall be able to retrieve search post results that contain the searched keyword in their title, tags.
- Users shall be able to retrieve other search post results that contain keywords, which can be fetched using the Wikidata subclass property.

As an example, when "couch" is searched, related seating items should also be returned, such as bench, sofa and chair.

PF2:

- Users shall be able to earn achievements and view them on their profile when required activity is done.

As an example, users should earn "Commenter" achievement and corresponding experience points when they comment on a post.


PF3:

- Users shall be able to update their profile picture
- Users shall be able to follow/unfollow other users
- Users shall be able to follow/unfollow categories

As an example, when users upload ".jpeg" format images to set as their profile picture, it can be viewed by other users in their profile. Furthermore, when a user or a category is followed, its content can be viewed in the feed.


PF4:

- Users shall be able to join tournaments under categories with their own posts.
- Users shall be ranked based on the interaction they received with the entered post.
- Users shall be awarded with the prize when they finish weekly tournaments in top 3.

As an example, when a user joins the tournament and receives the highest interaction, he/she should earn 30 experience points.

## Domain-Specific Features

### Acceptance Criteria & Examples

## API and Documentation

### Acceptance Criteria & Examples

## Standards

### Acceptance Criteria & Examples

## Testing Strategies

### Acceptance Criteria & Examples

**Comment by oguzkagnici** [comment]
PF2 Progress:
PR: #344 
Issues: #343

**Comment by yektaercul** [comment]
AD1 Progress
PR: #376 
Issues: #377

**Comment by oguzkagnici** [comment]
PF4 Progress: DONE
PR: #360 , #309 , #332 
Issues: #308 , #310 , #355

**Comment by yektaercul** [comment]
AD2 Progress: Created a new issue and assigned it.
PR: N/A
Issues: #401

**Comment by yektaercul** [comment]
AD3 Progress: Created a new issue and assigned it.
PR: N/A
Issues: #404

**Comment by tuluyhansozen** [comment]
Test Related All Issues 

- [Unit Tests For Comment and File Services](https://github.com/bounswe/bounswe2024group8/issues/388)
- [Frontend - Unit Tests For Search Results](https://github.com/bounswe/bounswe2024group8/issues/394)
- [Frontend - Unit Tests For Leaderboard Page](https://github.com/bounswe/bounswe2024group8/issues/393)
- [Frontend - Unit Tests For Tournament Info Component](https://github.com/bounswe/bounswe2024group8/issues/392)
- [Mobile - Connecting Leaderboard screen to backend](https://github.com/bounswe/bounswe2024group8/issues/382)
- [Backend - Write unit tests for backend](https://github.com/bounswe/bounswe2024group8/issues/366)
- [Create Unit Tests For Comment Service](https://github.com/bounswe/bounswe2024group8/issues/173)
- [Implement Unit Tests for Post Service layer](https://github.com/bounswe/bounswe2024group8/issues/165)
- [Implement User Service Unit tests](https://github.com/bounswe/bounswe2024group8/issues/164)
- [Add Test Information to Milestone](https://github.com/bounswe/bounswe2024group8/issues/193)
- [Frontend - Integration Test](https://github.com/bounswe/bounswe2024group8/issues/407)
- [Integration Test Scenarios for Backend](https://github.com/bounswe/bounswe2024group8/issues/406)
- [Integration Test For Backend](https://github.com/bounswe/bounswe2024group8/issues/405)

**Comment by oguzkagnici** [comment]
DSF1 Progress: DONE
PR: #265 , #400 , #247 
Issues: #200 , #201 , #259 , #275 , #367

**Comment by oguzkagnici** [comment]
DSF2 Progress: DONE
PR: #290 
Issue: #291 , #368

**Comment by oguzkagnici** [comment]
## Future Plans:

- [ ] Implement User Search
- [ ] Implement Scroll Render
- [ ] Annotation Protocol, separating the database
- [ ] Design post form structure

**Comment by TurkerErdem99** [comment]
S1 Progress: Created a new issue.
PR: N/A
Issues: #408

**Comment by TurkerErdem99** [comment]
S2 Progress: Created a new issue.
PR: N/A
Issues: #409

**Comment by TurkerErdem99** [comment]
S3 Progress: DONE
PR: [#326](https://github.com/bounswe/bounswe2024group8/pull/326)

**Comment by TurkerErdem99** [comment]
The [link](https://github.com/bounswe/bounswe2024group8/wiki/Meeting-Notes-9-%E2%80%90-Dec-3) of today's meeting notes is added into the description.

**Pull request merged**
